version: 2.1
_common:
  node-docker: &node-docker
    - image: circleci/node:10.13.0
  restore-cache: &restore-cache
    keys:
      - bootstrap-v1-{{ .Branch }}-{{ .Revision }}
  attach-workspace: &attach-workspace
    at: .

jobs:
  bootstrap:
    docker: *node-docker
    steps:
      - restore_cache: *restore-cache
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install deps
          command: npm install
      - save_cache:
          key: bootstrap-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.

  test:
    docker: *node-docker
    steps:
      - restore_cache: *restore-cache
      - checkout
      - run:
          name: Install deps
          command: npm install
      - run:
          name: Run tests
          command: npm run test:once

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - bootstrap
      - test